[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "robotics"
readme  = "README.md"

title = "MATteRIX framework for lab automation"
author = "MATteRIX Project Developers"
maintainer = "MATteRIX Project Developers"
description="Extension providing main framework interfaces and abstractions for robotic lab automation learning."
repository = "https://github.com/ac-rad/MATteRIX.git"
keywords = ["kit", "matterix", "isaaclab", "robotics", "lab", "automation"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "matterix"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
