[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title =  "MATteRIX Assets"
description="Extension containing configuration instances of different assets and sensors"
readme  = "docs/README.md"
repository = "https://github.com/ac-rad/MATteRIX.git"
category = "robotics"
keywords = ["kit", "robotics", "assets", "isaaclab"]

[dependencies]
"matterix" = {}
"isaaclab" = {}

[core]
reloadable = false

# Main python module this extension provides.
[[python.module]]
name = "matterix_assets"
