[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title =  "Matterix Environments"
description="Extension containing suite of environments for lab automation robot learning."
readme  = "docs/README.md"
repository = "https://github.com/ac-rad/Matterix.git"
category = "robotics"
keywords = ["kit", "robotics", "rl", "il", "isaaclab"]

[dependencies]
"matterix" = {}
"matterix_assets" = {}
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}

[core]
reloadable = false

# Main python module this extension provides.
[[python.module]]
name = "matterix_tasks"
